permalink: pretty

excerpt_separator: "<!--end excerpt-->"
paginate: 5
paginate_path: "/page/:num"

safe: true
lsi: false
highlighter: rouge
markdown: kramdown

static_url: /blog/static/
production_url : "http://siggame.github.io/blog/"

gems:
  - jekyll-paginate
