permalink: pretty

excerpt_separator: "<!--end excerpt-->"
paginate: 5
paginate_path: "blog/page/:num"

safe: true
lsi: false
highlighter: rouge
markdown: kramdown

static_url: /static/
production_url : "http://blog.megaminerai.com"

gems:
  - jekyll-paginate
